title: <p align="center"> Augusto Dos Santos </p>

logo: "/images/picture.png?raw=true"  

description:
  <p align="center">
  <a href="pdf/resume.pdf">Curriculum</a> |
  <a href="linkedin.com/in/augusto-dos-santos-a226622b6">LinkedIn</a> |
  <a href="https://github.com/augustosz">GitHub</a>
  </p>
  
  <p align="justify">
  Soy Analista en Sistemas Informáticos. 
  <br><br>
  Soy un analista de datos junior apasionado por transformar datos en insights accionables para el negocio. Mi enfoque se centra en comprender las necesidades del negocio y traducir preguntas complejas en análisis claros y visualizaciones efectivas. 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
