title: <p align="center"> Augusto Dos Santos </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Curriculum</a> |
  <a href="linkedin.com/in/augusto-dos-santos-a226622b6">LinkedIn</a> |
  <a href="https://github.com/augustosz">GitHub</a>
  </p>
  
  <p align="justify">
  Soy Analista en Sistemas Informáticos con conocimientos en administración de bases de datos, soporte técnico y desarrollo web. 
  <br><br>
  Me especializo en análisis de datos y automatización de procesos para mejorar la eficiencia operativa. Tengo un enfoque proactivo para resolver problemas técnicos y colaboro con equipos interdisciplinarios para desarrollar soluciones tecnológicas innovadoras.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
